stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - docker build -t registry.gitlab.com/<your-username>/<repo-name>:latest .
    - docker push registry.gitlab.com/<your-username>/<repo-name>:latest

deploy:
  stage: deploy
  script:
    - echo "Deploy stage pending integration with cloud tools"
