stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: node:16  # Use an official Node.js Docker image
  script:
    - npm install
    - npm test

build:
  stage: build
  image: docker:20.10.24  # Use Docker to build and push images
  services:
    - docker:20.10.24-dind
  variables:
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  script:
    - docker build -t highmood2k/devops-project .
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin
    - docker push highmood2k/devops-project
