stages:
  - test
  - build
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm test

build:
  stage: build
  script:
    - docker build -t highmood2k/devops-project:latest .
    - docker push highmood2k/devops-project:latest

deploy:
  stage: deploy
  script:
    - echo "Deploy stage pending integration with cloud tools"
